# Generated by Django 6.0.4 on 2026-04-25 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('return', 'Return window'), ('warranty', 'Warranty')], max_length=16)),
                ('send_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_events', to='purchases.purchase')),
            ],
            options={
                'ordering': ['send_at'],
                'constraints': [models.UniqueConstraint(fields=('purchase', 'kind', 'send_at'), name='uniq_event_purchase_kind_send_at')],
            },
        ),
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('return', 'Return window'), ('warranty', 'Warranty')], max_length=16)),
                ('days_before', models.PositiveSmallIntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', 'days_before'],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'days_before'), name='uniq_rule_user_kind_days')],
            },
        ),
    ]
